# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

[general]
# Directories to search for templates, relative to the crate root.
dirs = [
    "src/bindings/alicorn/templates",
    "src/scaffolding/templates",
]

[[syntax]]
name = "alc"

[[syntax]]
name = "rs"
